baseURL: https://example.com/
languageCode: en-us
title: Guangyao's blog
theme: hugo-theme-prav
# pygmentsCodeFences: 'true'
# pygmentsStyle: perldoc
ignoreErrors:
  "error-missing-instagram-accesstoken"
params:
  author: Guangyao Zhao
  authorBlurb: To err is human, to forgive is divine.
  authorImgPath: /img/author.png
social:
  email: zhaoguangyao1991@163.com
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight: 
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: xcode
    tabWidth: 4
